# Automatically generated by GPRPy
import os
import gprpy.gprpy as gp

folder = 'C:/Users/abate/OneDrive/Documents/Github/CCR_Geophysics/GPR data_20260112/unencrypted_Lineset/Lineset/'
files = ['line1.dt1', 'line2.dt1', 'line3.dt1']

results = {}

for file in files:
    filepath = os.path.join(folder, file)

    mygpr = gp.gprpyProfile()
    mygpr.importdata(filepath)
    mygpr.setZeroTime(2.5)
    mygpr.remMeanTrace(9999999999)
    mygpr.tpowGain(1.7)
    mygpr.dewow(3)
    mygpr.smooth(2)
    mygpr.setVelocity(0.06)
    mygpr.fkMigration()

    results[file] = mygpr
    print(f"Done processing: {file}")