# Automatically generated by GPRPy
import os
import gprpy.gprpy as gp
import matplotlib.pyplot as plt
import numpy as np
from scipy.signal import firwin, filtfilt
from scipy.ndimage import zoom

folder = 'C:/Users/abate/OneDrive/Documents/Github/CCR_Geophysics/GPR data_20260112/unencrypted_Lineset/Lineset/'
files = ['line1.dt1', 'line2.dt1', 'line3.dt1', 'line4.dt1', 'line5.dt1', 'line6.dt1']

output_folder = os.path.join(folder, 'pdf_outputs')
os.makedirs(output_folder, exist_ok=True)

results = {}

for file in files:
    filepath = os.path.join(folder, file)

    mygpr = gp.gprpyProfile()
    mygpr.importdata(filepath)
    mygpr.setZeroTime(2.5)
    mygpr.remMeanTrace(9999999999)
    mygpr.tpowGain(1.7)
    mygpr.dewow(3)
    mygpr.smooth(2)
    mygpr.setVelocity(0.06)
    mygpr.fkMigration()

    results[file] = mygpr

    # --- Wavenumber (kz) filter along depth axis ---
    # Corners in cycles/m: [stop, pass, pass, stop] (trapezoidal bandpass)
    kz_corners = [0.5, 5.0, 15.0, 17.0]

    dz = (mygpr.twtt[1] - mygpr.twtt[0]) / 2 * 0.06  # sample interval in meters
    fs_z = 1.0 / dz                                  # spatial sampling frequency (cycles/m)
    nyq = fs_z / 2.0

    # Normalize corners to Nyquist
    low_stop, low_pass, high_pass, high_stop = [k / nyq for k in kz_corners]

    # Build FIR bandpass filter (along depth/rows)
    numtaps = 101
    fir_coeff = firwin(numtaps, [low_pass, high_pass], pass_zero=False, window='hamming')

    data = mygpr.data.astype(float)
    data_filtered = filtfilt(fir_coeff, [1.0], data, axis=0)  # axis=0 = depth direction

    # --- 2x interpolation in x and z for plotting only ---
    data_interp = zoom(data_filtered, zoom=2, order=1)  # bilinear, 2x in both axes

    # Recompute axes to match interpolated grid
    depth = (mygpr.twtt / 2) * 0.06
    x_interp = np.linspace(mygpr.profilePos[0], mygpr.profilePos[-1], data_interp.shape[1])
    z_interp = np.linspace(depth[0], depth[-1], data_interp.shape[0])

    # --- Save as PDF ---
    fig, ax = plt.subplots(figsize=(12, 6))
    ax.imshow(
        data_interp,
        aspect='auto',
        cmap='bwr',
        extent=[x_interp[0], x_interp[-1], z_interp[-1], z_interp[0]],
        vmin=-np.percentile(np.abs(data_interp), 95),  # symmetric clip for bwr
        vmax= np.percentile(np.abs(data_interp), 95)
    )
    ax.set_xlabel('Profile position (m)')
    ax.set_ylabel('Depth (m)')
    ax.set_title(f'GPR Profile: {file}')

    pdf_name = os.path.splitext(file)[0] + '.pdf'
    pdf_path = os.path.join(output_folder, pdf_name)
    fig.savefig(pdf_path, bbox_inches='tight', dpi=150)
    plt.close(fig)

    print(f"Done processing: {file}")